<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Exemplo4.aspx.cs" Inherits="UNIP2024Forms.Exemplo4" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <asp:FormView ID="FormView1" runat="server" AllowPaging="True" DataSourceID="ObjectDataSource1">
        <EditItemTemplate>
            RowError:
            <asp:TextBox ID="RowErrorTextBox" runat="server" Text='<%# Bind("RowError") %>' />
            <br />
            RowState:
            <asp:TextBox ID="RowStateTextBox" runat="server" Text='<%# Bind("RowState") %>' />
            <br />
            Table:
            <asp:TextBox ID="TableTextBox" runat="server" Text='<%# Bind("Table") %>' />
            <br />
            ItemArray:
            <asp:TextBox ID="ItemArrayTextBox" runat="server" Text='<%# Bind("ItemArray") %>' />
            <br />
            HasErrors:
            <asp:CheckBox ID="HasErrorsCheckBox" runat="server" Checked='<%# Bind("HasErrors") %>' />
            <br />
            <asp:LinkButton ID="UpdateButton" runat="server" CausesValidation="True" CommandName="Update" Text="Update" />
            &nbsp;<asp:LinkButton ID="UpdateCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
        </EditItemTemplate>
        <InsertItemTemplate>
            RowError:
            <asp:TextBox ID="RowErrorTextBox" runat="server" Text='<%# Bind("RowError") %>' />
            <br />
            RowState:
            <asp:TextBox ID="RowStateTextBox" runat="server" Text='<%# Bind("RowState") %>' />
            <br />
            Table:
            <asp:TextBox ID="TableTextBox" runat="server" Text='<%# Bind("Table") %>' />
            <br />
            ItemArray:
            <asp:TextBox ID="ItemArrayTextBox" runat="server" Text='<%# Bind("ItemArray") %>' />
            <br />
            HasErrors:
            <asp:CheckBox ID="HasErrorsCheckBox" runat="server" Checked='<%# Bind("HasErrors") %>' />
            <br />
            <asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" CommandName="Insert" Text="Insert" />
            &nbsp;<asp:LinkButton ID="InsertCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
        </InsertItemTemplate>
        <ItemTemplate>
            RowError:
            <asp:Label ID="RowErrorLabel" runat="server" Text='<%# Bind("RowError") %>' />
            <br />
            RowState:
            <asp:Label ID="RowStateLabel" runat="server" Text='<%# Bind("RowState") %>' />
            <br />
            Table:
            <asp:Label ID="TableLabel" runat="server" Text='<%# Bind("Table") %>' />
            <br />
            ItemArray:
            <asp:Label ID="ItemArrayLabel" runat="server" Text='<%# Bind("ItemArray") %>' />
            <br />
            HasErrors:
            <asp:CheckBox ID="HasErrorsCheckBox" runat="server" Checked='<%# Bind("HasErrors") %>' Enabled="false" />
            <br />

        </ItemTemplate>
    </asp:FormView>
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="ObjectDataSource1">
        <Columns>
            <asp:CommandField ShowSelectButton="True" />
            <asp:BoundField DataField="RowError" HeaderText="RowError" SortExpression="RowError" />
            <asp:BoundField DataField="RowState" HeaderText="RowState" ReadOnly="True" SortExpression="RowState" />
            <asp:CheckBoxField DataField="HasErrors" HeaderText="HasErrors" ReadOnly="True" SortExpression="HasErrors" />
        </Columns>
    </asp:GridView>
    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" SelectMethod="Select" TypeName="UNIP2024Forms.App_Code.Banco+DtPessoaDataTable"></asp:ObjectDataSource>

</asp:Content>
